import type { CalendarEvent } from "./types"

// Additional calendar events: 代車・レンタカー、車検
export const extraCalendarEvents: CalendarEvent[] = [
  // 代車・レンタカー
  {
    id: "cal-011",
    title: "山本様 代車貸出",
    type: "loaner",
    typeJa: "代車",
    date: "2026-03-03",
    startTime: "13:00",
    endTime: "13:30",
    location: "店舗",
    customerId: "c-003",
    customerName: "山本 健一",
    vehicleName: "ヴィッツ（代車）",
    status: "confirmed",
    statusJa: "確定",
    notes: "車検入庫のため3日間貸出。3/6返却予定。",
    googleCalendarId: "gcal_loaner001",
  },
  {
    id: "cal-012",
    title: "山本様 代車返却",
    type: "loaner",
    typeJa: "代車",
    date: "2026-03-06",
    startTime: "10:00",
    endTime: "10:30",
    location: "店舗",
    customerId: "c-003",
    customerName: "山本 健一",
    vehicleName: "ヴィッツ（代車）",
    status: "scheduled",
    statusJa: "予定",
    notes: "車検完了引渡しと同時に代車返却。",
    googleCalendarId: "gcal_loaner002",
  },
  // 車検
  {
    id: "cal-013",
    title: "山本様 車検",
    type: "shaken",
    typeJa: "車検",
    date: "2026-03-06",
    startTime: "09:00",
    endTime: "17:00",
    location: "提携整備工場",
    customerId: "c-003",
    customerName: "山本 健一",
    vehicleName: "トヨタ プリウス 2021年式",
    status: "scheduled",
    statusJa: "予定",
    notes: "車検基本整備。追加整備の可能性あり。",
    googleCalendarId: "gcal_shaken001",
  },
  {
    id: "cal-014",
    title: "高橋様 車検リマインド",
    type: "shaken",
    typeJa: "車検",
    date: "2026-03-15",
    startTime: "10:00",
    endTime: "10:30",
    customerId: "c-005",
    customerName: "高橋 美咲",
    vehicleName: "BMW 3シリーズ 2021年式",
    agentId: "agent-shaken-remind",
    agentName: "車検リマインドエージェント",
    status: "scheduled",
    statusJa: "予定",
    notes: "車検満了1ヶ月前リマインド。LINE送信予定。",
    googleCalendarId: "gcal_shaken002",
  },
  {
    id: "cal-015",
    title: "佐藤様 レンタカー手配",
    type: "loaner",
    typeJa: "レンタカー",
    date: "2026-03-08",
    startTime: "09:00",
    endTime: "09:30",
    location: "店舗",
    customerId: "c-002",
    customerName: "佐藤 花子",
    vehicleName: "ノート（レンタカー）",
    status: "scheduled",
    statusJa: "予定",
    notes: "納車待ちのお客様へレンタカー手配。5日間。",
    googleCalendarId: "gcal_loaner003",
  },
]
