import type { Agent, ApprovalItem, ActivityEvent, Vehicle, KPI, Customer } from "./types"

export const agents: Agent[] = [
  // === フェーズ1: 仕入れ ===
  {
    id: "agent-aa-watcher",
    name: "AA Market Watcher",
    nameJa: "AA相場ウォッチャー",
    role: "Auction Monitoring & ROI Analysis",
    roleJa: "オークション監視・STRランキング連携",
    phase: "purchasing",
    phaseJa: "仕入れ",
    schedule: "daily",
    scheduleJa: "AA開催日前に自動起動",
    status: "active",
    currentTask: "Scanning USS Tokyo based on STR ranking",
    currentTaskJa: "STRランキング上位車種をUSS東京でスキャン中",
    completedToday: 12,
    tokenUsage: 95000,
    tokenBudget: 400000,
    skills: ["purchase-advisor", "WebFetch", "Insight:STRランキング"],
  },
  {
    id: "agent-trade-in",
    name: "Trade-in Advisor",
    nameJa: "買取・下取り査定サポート",
    role: "Instant Trade-in Pricing",
    roleJa: "即時査定・交渉フレーズ提示",
    phase: "purchasing",
    phaseJa: "仕入れ",
    schedule: "on-demand",
    scheduleJa: "来店時オンデマンド",
    status: "idle",
    currentTask: "Waiting for trade-in request",
    currentTaskJa: "買取依頼を待機中",
    completedToday: 3,
    tokenUsage: 28000,
    tokenBudget: 200000,
    skills: ["purchase-advisor", "Insight:市場相場"],
  },

  // === フェーズ2: 在庫管理・価格設定 ===
  {
    id: "agent-dynamic-pricing",
    name: "Dynamic Pricing Agent",
    nameJa: "在庫価格自動調整エージェント",
    role: "Daily Price Optimization",
    roleJa: "Insight価格アラート連携・在庫健全性に基づく最適化",
    phase: "inventory",
    phaseJa: "在庫管理",
    schedule: "daily",
    scheduleJa: "毎朝自動実行",
    status: "active",
    currentTask: "Syncing with Insight price alerts",
    currentTaskJa: "Insight価格アラートと連携中（高2/適正5/低1）",
    completedToday: 8,
    tokenUsage: 185000,
    tokenBudget: 500000,
    skills: ["dynamic-pricing", "Insight:価格アラート", "Insight:在庫健全性"],
  },
  {
    id: "agent-stale-inventory",
    name: "Stale Inventory Alert",
    nameJa: "滞留在庫アラートエージェント",
    role: "Long-term Stock Warning",
    roleJa: "Insight在庫健全性連携・90日超在庫の判断",
    phase: "inventory",
    phaseJa: "在庫管理",
    schedule: "weekly",
    scheduleJa: "週次",
    status: "active",
    currentTask: "Insight: 90日超在庫 8台検出",
    currentTaskJa: "Insight連携: 90日超在庫 8台の処分判断中",
    completedToday: 1,
    tokenUsage: 32000,
    tokenBudget: 100000,
    skills: ["Insight:在庫健全性", "Insight:回転率"],
  },

  // === フェーズ3: 集客 ===
  {
    id: "agent-sns-posting",
    name: "SNS Auto Poster",
    nameJa: "SNS自動投稿エージェント",
    role: "Daily Social Media Content",
    roleJa: "STR上位車種・トレンド連携投稿生成",
    phase: "marketing",
    phaseJa: "集客",
    schedule: "daily",
    scheduleJa: "毎日",
    status: "waiting",
    currentTask: "Waiting for approval: Alphard/Vezel posts",
    currentTaskJa: "承認待ち: アルファード・ヴェゼル特集（STR上位）",
    completedToday: 2,
    tokenUsage: 67000,
    tokenBudget: 200000,
    skills: ["sns-strategy", "Insight:STRランキング", "Insight:トレンド"],
  },
  {
    id: "agent-competitor-watch",
    name: "Competitor Monitor",
    nameJa: "競合価格モニタリングエージェント",
    role: "Competitor Price Tracking",
    roleJa: "Insight競合動向連携・商圏内店舗監視",
    phase: "marketing",
    phaseJa: "集客",
    schedule: "daily",
    scheduleJa: "毎日（Insight連携）",
    status: "active",
    currentTask: "Auto Plaza +8%, Car Select -3%",
    currentTaskJa: "オートプラザ+8%増、カーセレクト-3%減検出",
    completedToday: 1,
    tokenUsage: 44000,
    tokenBudget: 150000,
    skills: ["WebFetch", "Insight:競合動向", "Insight:全国ランキング"],
  },

  // === フェーズ4: 接客・商談 ===
  {
    id: "agent-inquiry-reply",
    name: "Inquiry Auto-Reply",
    nameJa: "問い合わせ自動返信エージェント",
    role: "Web/LINE/Email Auto Response",
    roleJa: "Web・LINE・メール自動返信",
    phase: "sales",
    phaseJa: "接客・商談",
    schedule: "realtime",
    scheduleJa: "リアルタイム",
    status: "active",
    currentTask: "Replied to LINE inquiry 2 min ago",
    currentTaskJa: "2分前にLINE問い合わせに返信",
    completedToday: 18,
    tokenUsage: 156000,
    tokenBudget: 400000,
    skills: ["psychology-framework", "segment-adapter", "Insight:市場相場"],
  },
  {
    id: "agent-sales-support",
    name: "Sales Support Agent",
    nameJa: "商談リアルタイムサポート",
    role: "In-store Negotiation Assistant",
    roleJa: "Insight相場連携・競合比較トーク支援",
    phase: "sales",
    phaseJa: "接客・商談",
    schedule: "on-demand",
    scheduleJa: "オンデマンド",
    status: "idle",
    currentTask: "Ready for next consultation",
    currentTaskJa: "次の商談を待機中",
    completedToday: 5,
    tokenUsage: 89000,
    tokenBudget: 300000,
    skills: ["Insight:競合動向", "Insight:価格アラート"],
  },

  // === フェーズ5: 成約・納車 ===
  {
    id: "agent-contract-gen",
    name: "Contract Generator",
    nameJa: "契約書・見積書自動生成",
    role: "Document Auto-generation",
    roleJa: "見積書・契約書PDF出力",
    phase: "contract",
    phaseJa: "成約・納車",
    schedule: "on-demand",
    scheduleJa: "オンデマンド",
    status: "idle",
    currentTask: "No pending requests",
    currentTaskJa: "リクエスト待機中",
    completedToday: 2,
    tokenUsage: 23000,
    tokenBudget: 150000,
    skills: ["docx", "pdf"],
  },

  // === フェーズ6: アフターフォロー ===
  {
    id: "agent-follow-up",
    name: "Customer Follow-up",
    nameJa: "顧客フォローアップエージェント",
    role: "Post-sale Automatic Contact",
    roleJa: "納車後フォロー・口コミ依頼・車検リマインド",
    phase: "aftersales",
    phaseJa: "アフター",
    schedule: "daily",
    scheduleJa: "毎日",
    status: "active",
    currentTask: "Sending 7-day follow-up to 3 customers",
    currentTaskJa: "3名に納車7日後フォローを送信中",
    completedToday: 12,
    tokenUsage: 78000,
    tokenBudget: 250000,
    skills: ["reputation-manager"],
  },
  {
    id: "agent-review-patrol",
    name: "Review Patrol",
    nameJa: "口コミ巡回エージェント",
    role: "Review Monitoring & Reply",
    roleJa: "Google・カーセンサー口コミ監視・返信案生成",
    phase: "aftersales",
    phaseJa: "アフター",
    schedule: "daily",
    scheduleJa: "毎朝",
    status: "waiting",
    currentTask: "New negative review detected - awaiting response approval",
    currentTaskJa: "ネガティブ口コミ検出 - 返信承認待ち",
    completedToday: 4,
    tokenUsage: 45000,
    tokenBudget: 200000,
    skills: ["reputation-manager", "WebFetch"],
  },
  {
    id: "agent-shaken-remind",
    name: "Shaken Reminder",
    nameJa: "車検・点検リマインドエージェント",
    role: "Maintenance Schedule Alerts",
    roleJa: "車検・点検期限の自動LINE/SMS送信",
    phase: "aftersales",
    phaseJa: "アフター",
    schedule: "daily",
    scheduleJa: "毎日",
    status: "idle",
    currentTask: "5 reminders sent today",
    currentTaskJa: "本日5件のリマインド送信済み",
    completedToday: 5,
    tokenUsage: 18000,
    tokenBudget: 100000,
    skills: ["psychology-framework"],
  },
]

export const approvalQueue: ApprovalItem[] = [
  {
    id: "appr-001",
    agentId: "agent-dynamic-pricing",
    agentName: "在庫価格自動調整エージェント",
    type: "pricing",
    typeJa: "価格調整",
    title: "Price adjustment for Mercedes C200",
    titleJa: "メルセデス C200 価格調整【Insight連携】",
    description: "Insight price alert: Listed as 'High Price'. 67 days listed, recommend reduction",
    descriptionJa: "Insight価格アラート: 「高価格」判定。67日経過、値下げ推奨",
    priority: "high",
    createdAt: "2026-03-03T09:15:00Z",
    data: { currentPrice: 3280000, suggestedPrice: 2980000, comparables: 47, daysListed: 67, insightAlert: "高価格" },
    reasoning: "Insight price alert flagged as 'High Price'. 67 days listed (exceeds 61-90 day warning zone). Market average from Insight data is 2,950,000 JPY. Recommend reducing to 2,980,000 JPY.",
    reasoningJa: "Insight価格アラートで「高価格」フラグ。掲載67日（61-90日警告ゾーン）。Insightの市場相場は295万円。298万円への値下げを推奨。",
  },
  {
    id: "appr-002",
    agentId: "agent-aa-watcher",
    agentName: "AA相場ウォッチャー",
    type: "purchase",
    typeJa: "仕入承認",
    title: "Purchase bid for Alphard at USS Tokyo",
    titleJa: "USS東京 アルファード 入札承認【STR1位】",
    description: "STR ranking #1 (28.5%) - High demand vehicle found at USS auction",
    descriptionJa: "STRランキング1位（28.5%）の高需要車種をUSS東京で発見",
    priority: "high",
    createdAt: "2026-03-03T09:05:00Z",
    data: { estimatedPrice: 4200000, maxBid: 4500000, margin: 250000, matchingCustomers: 5, auctionIn: "45分", strRank: 1, strRate: "28.5%" },
    reasoning: "Toyota Alphard is STR ranking #1 in Tokyo area (28.5% sell-through rate). 5 active customers match. Market price trending +8.3%. High confidence ROI.",
    reasoningJa: "トヨタ アルファードはInsight STRランキング1位（28.5%）。5名の顧客マッチ。市場価格+8.3%上昇トレンド。高ROI見込み。",
  },
  {
    id: "appr-003",
    agentId: "agent-review-patrol",
    agentName: "口コミ巡回エージェント",
    type: "review-reply",
    typeJa: "口コミ返信",
    title: "Negative review detected - response needed",
    titleJa: "ネガティブ口コミ検出 - 返信案承認",
    description: "Google review (2 stars) requires immediate response",
    descriptionJa: "Googleに星2レビュー投稿あり。即時返信推奨",
    priority: "high",
    createdAt: "2026-03-03T08:50:00Z",
    data: { platform: "Google", rating: 2, reviewer: "Y.S様" },
    reasoning: "Negative review posted 3 hours ago. Quick response (within 24h) improves perception. Generated empathetic response acknowledging concern and offering direct contact.",
    reasoningJa: "3時間前に投稿されたネガティブレビュー。24時間以内の返信が印象改善に効果的。懸念に共感し直接連絡先を提示する返信案を生成済み。",
  },
  {
    id: "appr-004",
    agentId: "agent-sns-posting",
    agentName: "SNS自動投稿エージェント",
    type: "sns-post",
    typeJa: "SNS投稿",
    title: "Instagram/TikTok posts ready",
    titleJa: "STR上位車種の投稿案 3件【Insight連携】",
    description: "Featuring STR top 3: Alphard, Vezel, Harrier",
    descriptionJa: "STRランキング上位3車種: アルファード・ヴェゼル・ハリアー特集",
    priority: "medium",
    createdAt: "2026-03-03T08:30:00Z",
    data: { posts: 3, platforms: ["Instagram", "TikTok", "LINE"], strTop3: ["アルファード", "ヴェゼル", "ハリアー"] },
    reasoning: "Content based on Insight STR ranking. Alphard (#1, 28.5%), Vezel (#2, 24.2%), Harrier (#3, 22.8%). These high-demand vehicles maximize engagement.",
    reasoningJa: "Insight STRランキングに基づくコンテンツ。アルファード(1位,28.5%)、ヴェゼル(2位,24.2%)、ハリアー(3位,22.8%)。高需要車種で反響最大化。",
  },
  {
    id: "appr-005",
    agentId: "agent-follow-up",
    agentName: "顧客フォローアップエージェント",
    type: "follow-up",
    typeJa: "フォロー送信",
    title: "7-day follow-up: 3 customers",
    titleJa: "納車7日後フォロー: 3名",
    description: "Automated satisfaction check and review request",
    descriptionJa: "満足度確認と口コミ依頼メッセージ",
    priority: "medium",
    createdAt: "2026-03-03T08:20:00Z",
    data: { customers: 3, type: "7日後フォロー" },
    reasoning: "3 customers reached 7-day mark since delivery. Psychology-optimized message requesting Google review with direct link. 7-day timing has highest response rate.",
    reasoningJa: "3名が納車後7日経過。心理学に基づくタイミングでGoogle口コミ依頼（直リンク付き）。7日目が最も返信率が高い。",
  },
  {
    id: "appr-006",
    agentId: "agent-inquiry-reply",
    agentName: "問い合わせ自動返信エージェント",
    type: "inquiry-reply",
    typeJa: "問い合わせ返信",
    title: "LINE inquiry: Suzuki-sama",
    titleJa: "LINE問い合わせ: 鈴木様",
    description: "Interested in Honda Fit - draft reply ready",
    descriptionJa: "Honda Fit に興味あり - 返信案生成済み",
    priority: "low",
    createdAt: "2026-03-03T08:10:00Z",
    data: { channel: "LINE", vehicleId: "v-004", responseTime: "2分" },
    reasoning: "Suzuki-sama inquired about Honda Fit. Vehicle is in inspection (B+ grade). Reply includes current status, expected availability, and appointment suggestion. Psychology: reciprocity trigger included.",
    reasoningJa: "鈴木様がHonda Fitについて問い合わせ。車両は検査中（B+）。返信には現在のステータス、出品予定、来店提案を含む。心理学: 返報性トリガーを含む。",
  },
  {
    id: "appr-007",
    agentId: "agent-stale-inventory",
    agentName: "滞留在庫アラートエージェント",
    type: "transfer",
    typeJa: "業販・AA出品",
    title: "Stale inventory alert: 8 vehicles",
    titleJa: "滞留アラート: 8台【Insight在庫健全性】",
    description: "Insight: 90+ day inventory at 9% (8 units) - above healthy threshold",
    descriptionJa: "Insight在庫健全性: 90日超が9%（8台）- 健全水準超過",
    priority: "high",
    createdAt: "2026-03-03T08:00:00Z",
    data: { staleCount: 8, stalePercent: 9, turnoverRate: 6.3, avgDays: 49, insightRanking: "20位/21店" },
    reasoning: "Insight shows 90+ day inventory at 9% (8 units). Store ranking 20/21 in area. Turnover rate 6.3x (below average). Recommend aggressive wholesale for bottom 4 vehicles.",
    reasoningJa: "Insight在庫健全性: 90日超が9%（8台）。全国ランキング20位/21店。回転率6.3回/年（平均以下）。下位4台の業販処分を推奨。",
  },
  {
    id: "appr-008",
    agentId: "agent-competitor-watch",
    agentName: "競合価格モニタリングエージェント",
    type: "pricing",
    typeJa: "競合対策",
    title: "Competitor price change alert",
    titleJa: "競合価格変動アラート【Insight連携】",
    description: "Auto Plaza Shinjuku +8% inventory, recommend price review",
    descriptionJa: "オートプラザ新宿が在庫8%増。価格見直し推奨",
    priority: "medium",
    createdAt: "2026-03-03T07:45:00Z",
    data: { competitor: "オートプラザ新宿", change: "+8%", ourInventory: 89, theirInventory: 312 },
    reasoning: "Insight competitor data shows Auto Plaza Shinjuku increased inventory by 8% (now 312 units vs our 89). They may be preparing for price competition. Recommend preemptive price review on overlapping models.",
    reasoningJa: "Insight競合データ: オートプラザ新宿が在庫8%増（312台 vs 自店89台）。価格競争の可能性。重複車種の先行価格見直しを推奨。",
  },
]

export const activityFeed: ActivityEvent[] = [
  {
    id: "evt-001",
    agentId: "agent-dynamic-pricing",
    agentName: "価格調整",
    action: "Synced with Insight price alerts",
    actionJa: "Insight価格アラートと同期完了",
    timestamp: "2026-03-03T09:18:00Z",
    status: "success",
    details: "High:2, Optimal:5, Low:1",
    detailsJa: "高価格:2 / 適正:5 / 低価格:1",
  },
  {
    id: "evt-002",
    agentId: "agent-aa-watcher",
    agentName: "AA相場",
    action: "Found STR top vehicles at auction",
    actionJa: "STR上位車種をオークションで発見",
    timestamp: "2026-03-03T09:15:00Z",
    status: "info",
    details: "Alphard (STR #1), Vezel (STR #2)",
    detailsJa: "アルファード(STR1位)、ヴェゼル(STR2位)",
  },
  {
    id: "evt-003",
    agentId: "agent-inquiry-reply",
    agentName: "問い合わせ",
    action: "Auto-replied to 5 LINE inquiries",
    actionJa: "LINE問い合わせ5件に自動返信",
    timestamp: "2026-03-03T09:12:00Z",
    status: "success",
  },
  {
    id: "evt-004",
    agentId: "agent-review-patrol",
    agentName: "口コミ巡回",
    action: "Negative review detected - response pending",
    actionJa: "ネガティブ口コミ検出 - 返信承認待ち",
    timestamp: "2026-03-03T09:08:00Z",
    status: "warning",
    details: "Google 2-star review from Y.S様",
    detailsJa: "Google星2レビュー Y.S様",
  },
  {
    id: "evt-005",
    agentId: "agent-sns-posting",
    agentName: "SNS投稿",
    action: "Generated 3 posts for approval",
    actionJa: "3件の投稿案を生成、承認待ち",
    timestamp: "2026-03-03T09:05:00Z",
    status: "info",
    details: "Instagram, TikTok, LINE",
    detailsJa: "Instagram, TikTok, LINE",
  },
  {
    id: "evt-006",
    agentId: "agent-dynamic-pricing",
    agentName: "価格調整",
    action: "Price reduction recommended for 2 vehicles",
    actionJa: "2台の値下げを提案",
    timestamp: "2026-03-03T09:00:00Z",
    status: "info",
  },
  {
    id: "evt-007",
    agentId: "agent-aa-watcher",
    agentName: "AA相場",
    action: "Won bid: Lexus NX 350h at USS Nagoya",
    actionJa: "落札成功: レクサス NX 350h USS名古屋",
    timestamp: "2026-03-03T08:55:00Z",
    status: "success",
    details: "Won at 3,420,000 JPY (budget: 3,600,000)",
    detailsJa: "342万円で落札（予算: 360万円）",
  },
  {
    id: "evt-008",
    agentId: "agent-follow-up",
    agentName: "フォロー",
    action: "Sent 7-day follow-up to 3 customers",
    actionJa: "納車7日後フォローを3名に送信",
    timestamp: "2026-03-03T08:48:00Z",
    status: "success",
  },
  {
    id: "evt-009",
    agentId: "agent-competitor-watch",
    agentName: "競合監視",
    action: "Insight competitor data synced",
    actionJa: "Insight競合動向データを取得",
    timestamp: "2026-03-03T08:42:00Z",
    status: "warning",
    details: "Auto Plaza +8%, ranking 20/21",
    detailsJa: "オートプラザ+8%増、自店ランキング20位/21店",
  },
  {
    id: "evt-010",
    agentId: "agent-shaken-remind",
    agentName: "車検通知",
    action: "Sent 5 shaken reminders via LINE",
    actionJa: "5件の車検リマインドをLINE送信",
    timestamp: "2026-03-03T08:30:00Z",
    status: "success",
  },
]

export const vehicles: Vehicle[] = [
  {
    id: "v-001",
    make: "Toyota",
    model: "Crown Crossover",
    year: 2023,
    mileage: 12000,
    purchasePrice: 4200000,
    suggestedPrice: 4980000,
    status: "listed",
    statusJa: "出品中",
    imageUrl: "/placeholder.svg?height=200&width=320",
    grade: "4.5",
    color: "Black",
    colorJa: "ブラック",
    daysListed: 5,
    inquiries: 8,
    views: 234,
    source: "USS東京",
    vin: "JTE12345678901234",
  },
  {
    id: "v-002",
    make: "Mercedes-Benz",
    model: "C200",
    year: 2021,
    mileage: 23000,
    purchasePrice: 2800000,
    suggestedPrice: 2980000,
    status: "listed",
    statusJa: "出品中",
    imageUrl: "/placeholder.svg?height=200&width=320",
    grade: "4.0",
    color: "Silver",
    colorJa: "シルバー",
    daysListed: 21,
    inquiries: 0,
    views: 89,
    source: "HAA神戸",
    vin: "WDD20512345678901",
  },
  {
    id: "v-003",
    make: "BMW",
    model: "320i M Sport",
    year: 2022,
    mileage: 18000,
    purchasePrice: 0,
    suggestedPrice: 4420000,
    status: "pending-purchase",
    statusJa: "仕入承認待ち",
    imageUrl: "/placeholder.svg?height=200&width=320",
    grade: "4.5",
    color: "White",
    colorJa: "ホワイト",
    daysListed: 0,
    inquiries: 0,
    views: 0,
    source: "USS東京",
  },
  {
    id: "v-004",
    make: "Honda",
    model: "Fit",
    year: 2023,
    mileage: 8000,
    purchasePrice: 1650000,
    suggestedPrice: 1980000,
    status: "in-inspection",
    statusJa: "検査中",
    imageUrl: "/placeholder.svg?height=200&width=320",
    grade: "B+",
    color: "Blue",
    colorJa: "ブルー",
    daysListed: 0,
    inquiries: 0,
    views: 0,
    source: "JU岐阜",
  },
  {
    id: "v-005",
    make: "Toyota",
    model: "Alphard",
    year: 2023,
    mileage: 5000,
    purchasePrice: 5200000,
    suggestedPrice: 5980000,
    status: "listed",
    statusJa: "出品中",
    imageUrl: "/placeholder.svg?height=200&width=320",
    grade: "5.0",
    color: "White Pearl",
    colorJa: "ホワイトパール",
    daysListed: 3,
    inquiries: 14,
    views: 456,
    source: "USS名古屋",
  },
  {
    id: "v-006",
    make: "Mazda",
    model: "CX-5",
    year: 2022,
    mileage: 15000,
    purchasePrice: 2300000,
    suggestedPrice: 2800000,
    status: "listed",
    statusJa: "出品中",
    imageUrl: "/placeholder.svg?height=200&width=320",
    grade: "4.0",
    color: "White",
    colorJa: "ホワイト",
    daysListed: 7,
    inquiries: 3,
    views: 178,
    source: "HAA神戸",
  },
  {
    id: "v-007",
    make: "Lexus",
    model: "NX 350h",
    year: 2023,
    mileage: 9000,
    purchasePrice: 3420000,
    suggestedPrice: 4180000,
    status: "in-inspection",
    statusJa: "検査中",
    imageUrl: "/placeholder.svg?height=200&width=320",
    grade: "---",
    color: "Sonic Titanium",
    colorJa: "ソニックチタニウム",
    daysListed: 0,
    inquiries: 0,
    views: 0,
    source: "USS名古屋",
  },
  {
    id: "v-008",
    make: "Subaru",
    model: "Forester",
    year: 2021,
    mileage: 32000,
    purchasePrice: 1900000,
    suggestedPrice: 2380000,
    status: "listed",
    statusJa: "出品中",
    imageUrl: "/placeholder.svg?height=200&width=320",
    grade: "3.5",
    color: "Green",
    colorJa: "グリーン",
    daysListed: 18,
    inquiries: 1,
    views: 67,
    source: "JU岐阜",
  },
]

export const customers: Customer[] = [
  {
    id: "c-001",
    name: "田中 太郎",
    nameKana: "タナカ タロウ",
    phone: "090-1234-5678",
    email: "tanaka@example.com",
    preferences: {
      bodyTypes: ["SUV"],
      makes: ["マツダ", "トヨタ"],
      yearMin: 2020,
      mileageMax: 30000,
      colors: ["ホワイト", "ブラック"],
      features: ["安全装備充実"],
    },
    matchedVehicles: ["v-006"],
    matchScore: 94,
    status: "active",
    statusJa: "アクティブ",
    lastContact: "2026-03-02T15:30:00Z",
    source: "Web問い合わせ",
    sourceJa: "Web問い合わせ",
    notes: "予算300万円以下、白色SUV希望。週末来店予定。",
    registeredAt: "2026-02-17T10:00:00Z",
    budget: { min: 2000000, max: 3000000 },
  },
  {
    id: "c-002",
    name: "佐藤 花子",
    nameKana: "サトウ ハナコ",
    phone: "080-2345-6789",
    email: "sato.h@example.com",
    preferences: {
      bodyTypes: ["ミニバン"],
      makes: ["トヨタ"],
      yearMin: 2022,
      mileageMax: 20000,
      colors: ["ホワイトパール"],
      features: ["7人乗り", "両側パワースライドドア"],
    },
    matchedVehicles: ["v-005"],
    matchScore: 88,
    status: "negotiating",
    statusJa: "商談中",
    lastContact: "2026-03-03T08:00:00Z",
    source: "紹介",
    sourceJa: "紹介",
    notes: "アルファードに興味あり。試乗��望。",
    registeredAt: "2026-02-20T14:00:00Z",
    budget: { min: 4000000, max: 6500000 },
  },
  {
    id: "c-003",
    name: "山田 一郎",
    nameKana: "ヤマダ イチロウ",
    phone: "070-3456-7890",
    email: "yamada@example.com",
    preferences: {
      bodyTypes: ["セダン", "クーペ"],
      makes: ["BMW", "メルセデス・ベンツ"],
      yearMin: 2021,
      mileageMax: 25000,
      colors: [],
      features: ["スポーツパッケージ"],
    },
    matchedVehicles: ["v-003", "v-002"],
    matchScore: 82,
    status: "contacted",
    statusJa: "連絡済み",
    lastContact: "2026-03-01T11:00:00Z",
    source: "来店",
    sourceJa: "来店",
    notes: "BMW 3シリーズかCクラスを検討中。M Sportが第一希望。",
    registeredAt: "2026-02-25T16:00:00Z",
    budget: { min: 3000000, max: 4500000 },
  },
  {
    id: "c-004",
    name: "鈴木 美咲",
    nameKana: "スズキ ミサキ",
    phone: "090-4567-8901",
    email: "suzuki.m@example.com",
    preferences: {
      bodyTypes: ["コンパクト"],
      makes: ["ホンダ", "トヨタ"],
      yearMin: 2022,
      mileageMax: 15000,
      colors: ["ブルー", "レッド"],
      features: ["燃費良好", "駐車支援"],
    },
    matchedVehicles: ["v-004"],
    matchScore: 76,
    status: "active",
    statusJa: "アクティブ",
    lastContact: "2026-02-28T14:00:00Z",
    source: "Web問い合わせ",
    sourceJa: "Web問い合わせ",
    notes: "初めての車。コンパクトカー希望。200万円前後。",
    registeredAt: "2026-02-28T14:00:00Z",
    budget: { min: 1500000, max: 2200000 },
  },
  {
    id: "c-005",
    name: "高橋 健二",
    nameKana: "タカハシ ケンジ",
    phone: "080-5678-9012",
    email: "takahashi.k@example.com",
    preferences: {
      bodyTypes: ["SUV", "クロスオーバー"],
      makes: ["トヨタ", "レクサス"],
      yearMin: 2022,
      mileageMax: 15000,
      colors: ["ブラック", "グレー"],
      features: ["ハイブリッド", "本革シート"],
    },
    matchedVehicles: ["v-001", "v-007"],
    matchScore: 91,
    status: "active",
    statusJa: "アクティブ",
    lastContact: "2026-03-02T10:00:00Z",
    source: "リピーター",
    sourceJa: "リピーター",
    notes: "前回もうちで購入。レクサスNXかクラウンクロスオーバーに興味。",
    registeredAt: "2026-02-10T09:00:00Z",
    budget: { min: 3500000, max: 5500000 },
  },
  {
    id: "c-006",
    name: "伊藤 由美",
    nameKana: "イトウ ユミ",
    phone: "090-6789-0123",
    email: "ito.y@example.com",
    preferences: {
      bodyTypes: ["SUV"],
      makes: ["スバル"],
      yearMin: 2020,
      mileageMax: 40000,
      colors: ["グリーン", "ブルー"],
      features: ["AWD", "アイサイト"],
    },
    matchedVehicles: ["v-008"],
    matchScore: 85,
    status: "dormant",
    statusJa: "休眠",
    lastContact: "2026-02-10T13:00:00Z",
    source: "Web問い合わせ",
    sourceJa: "Web問い合わせ",
    notes: "フォレスター希望だが、最終連絡から3週間経過。再アプローチ推奨。",
    registeredAt: "2026-02-05T11:00:00Z",
    budget: { min: 1800000, max: 2800000 },
  },
]

export const kpis: KPI[] = [
  { label: "Monthly Revenue", labelJa: "月間売上", value: "47.2M", change: 12.5, trend: "up" },
  { label: "Active Inventory", labelJa: "在庫台数", value: "142", change: -3, trend: "down" },
  { label: "Avg Days to Sale", labelJa: "平均販売日数", value: "14.2", change: -18, trend: "up" },
  { label: "Token Efficiency", labelJa: "トークン効率", value: "94.2%", change: 2.1, trend: "up" },
]
