import type { Agent, ApprovalItem, ActivityEvent, Vehicle, KPI } from "./types"

export const agents: Agent[] = [
  {
    id: "agent-pricing",
    name: "Pricing Agent",
    nameJa: "価格算定エージェント",
    role: "Market Analysis & Pricing",
    roleJa: "市場分析・価格算定",
    status: "active",
    currentTask: "Analyzing auction data for Toyota Crown 2022",
    currentTaskJa: "トヨタ クラウン 2022年式のオークションデータを分析中",
    completedToday: 23,
    tokenUsage: 142000,
    tokenBudget: 500000,
  },
  {
    id: "agent-inspection",
    name: "Inspection Agent",
    nameJa: "車両検査エージェント",
    role: "Vehicle Inspection & Grading",
    roleJa: "車両検査・グレーディング",
    status: "waiting",
    currentTask: "Waiting for approval: Honda Fit inspection report",
    currentTaskJa: "承認待ち: Honda Fit 検査レポート",
    completedToday: 8,
    tokenUsage: 89000,
    tokenBudget: 300000,
  },
  {
    id: "agent-matching",
    name: "Customer Matching Agent",
    nameJa: "顧客マッチングエージェント",
    role: "Customer-Vehicle Matching",
    roleJa: "顧客・車両マッチング",
    status: "active",
    currentTask: "Cross-referencing 12 customer preferences with new inventory",
    currentTaskJa: "12件の顧客希望条件と新規在庫を照合中",
    completedToday: 45,
    tokenUsage: 203000,
    tokenBudget: 400000,
  },
  {
    id: "agent-listing",
    name: "Listing Agent",
    nameJa: "出品エージェント",
    role: "Vehicle Listing & Marketing",
    roleJa: "車両出品・マーケティング",
    status: "active",
    currentTask: "Generating listing photos and descriptions for 3 vehicles",
    currentTaskJa: "3台の車両写真・説明文を生成中",
    completedToday: 15,
    tokenUsage: 178000,
    tokenBudget: 350000,
  },
  {
    id: "agent-procurement",
    name: "Procurement Agent",
    nameJa: "仕入エージェント",
    role: "Auction Monitoring & Bidding",
    roleJa: "オークション監視・入札",
    status: "idle",
    currentTask: "Next auction scan in 14 minutes",
    currentTaskJa: "次回オークションスキャンまで14分",
    completedToday: 67,
    tokenUsage: 95000,
    tokenBudget: 600000,
  },
]

export const approvalQueue: ApprovalItem[] = [
  {
    id: "appr-001",
    agentId: "agent-pricing",
    agentName: "価格算定エージェント",
    type: "pricing",
    typeJa: "価格設定",
    title: "Price adjustment for Mercedes C200",
    titleJa: "メルセデス C200 価格調整",
    description: "Market analysis suggests 8% price reduction based on 47 comparable listings and 3-week listing age",
    descriptionJa: "47件の類似出品と3週間の掲載期間に基づき、8%の値下げを提案",
    priority: "high",
    createdAt: "2026-03-03T09:15:00Z",
    data: { currentPrice: 3280000, suggestedPrice: 2980000, comparables: 47 },
    reasoning: "Vehicle has been listed for 21 days without inquiries. Market average for similar vehicles (2021 C200, 15K-25K km) is 2,950,000 JPY. Recommend reducing to 2,980,000 JPY to generate leads while maintaining margin.",
    reasoningJa: "掲載開始から21日間問い合わせゼロ。類似車両（2021年式 C200, 1.5-2.5万km）の市場平均は295万円。リード獲得のため298万円への値下げを推奨。マージンは維持可能。",
  },
  {
    id: "appr-002",
    agentId: "agent-procurement",
    agentName: "仕入エージェント",
    type: "purchase",
    typeJa: "仕入承認",
    title: "Purchase bid for BMW 320i at USS Tokyo",
    titleJa: "USS東京 BMW 320i 入札承認",
    description: "Found a 2022 BMW 320i M Sport at USS auction matching 3 customer preferences",
    descriptionJa: "USS オークションにて2022年式 BMW 320i M Sport を発見。3件の顧客希望と合致",
    priority: "high",
    createdAt: "2026-03-03T09:05:00Z",
    data: { estimatedPrice: 3800000, maxBid: 4100000, margin: 320000, matchingCustomers: 3 },
    reasoning: "Grade 4.5 vehicle, 18,000km. Three active customers looking for similar spec. Estimated retail at 4,420,000 JPY gives healthy 320K margin even at max bid. Auction starts in 45 minutes.",
    reasoningJa: "グレード4.5、走行1.8万km。3名のアクティブ顧客が同スペックを希望中。推定小売価格442万円で最高入札額でも32万円のマージン確保可能。オークション開始まで45分。",
  },
  {
    id: "appr-003",
    agentId: "agent-inspection",
    agentName: "車両検査エージェント",
    type: "inspection",
    typeJa: "検査結果",
    title: "Inspection report: Honda Fit 2023",
    titleJa: "検査レポート: Honda Fit 2023年式",
    description: "AI inspection complete. Grade B+. Minor scratch on rear bumper detected",
    descriptionJa: "AI検査完了。グレードB+。リアバンパーに軽微な傷を検出",
    priority: "medium",
    createdAt: "2026-03-03T08:45:00Z",
    data: { grade: "B+", issues: 1, repairCost: 15000 },
    reasoning: "Overall vehicle condition is excellent. Single 3cm scratch on rear bumper, estimated repair cost 15,000 JPY. Recommend listing as-is with disclosure, or repair for upgraded grade to A-.",
    reasoningJa: "全体的な車両状態は良好。リアバンパーに3cmの傷1か所、修理費推定1.5万円。現状出品（傷開示）または修理してグレードA-への昇格を推奨。",
  },
  {
    id: "appr-004",
    agentId: "agent-matching",
    agentName: "顧客マッチングエージェント",
    type: "customer",
    typeJa: "顧客提案",
    title: "Customer outreach: Tanaka-sama",
    titleJa: "顧客アプローチ: 田中様",
    description: "Perfect match found. Recommend sending personalized proposal",
    descriptionJa: "最適な車両マッチを検出。パーソナライズ提案の送信を推奨",
    priority: "medium",
    createdAt: "2026-03-03T08:30:00Z",
    data: { customerId: "c-042", matchScore: 94, vehicleId: "v-018" },
    reasoning: "Tanaka-sama has been searching for a white SUV under 3M JPY for 2 weeks. New Mazda CX-5 2022 (white, 2.8M) matches 94% of stated preferences. High conversion probability based on engagement history.",
    reasoningJa: "田中様は2週間前から300万円以下の白色SUVを検索中。新着のマツダ CX-5 2022年式（白、280万円）が希望条件の94%に合致。過去の行動データから高い成約確率を予測。",
  },
  {
    id: "appr-005",
    agentId: "agent-listing",
    agentName: "出品エージェント",
    type: "listing",
    typeJa: "出品承認",
    title: "New listing: Toyota Alphard 2023",
    titleJa: "新規出品: トヨタ アルファード 2023年式",
    description: "Listing content generated. Photos enhanced, description optimized for SEO",
    descriptionJa: "出品コンテンツ生成完了。写真補正済み、SEO最適化済み説明文",
    priority: "low",
    createdAt: "2026-03-03T08:15:00Z",
    data: { photos: 24, price: 5980000 },
    reasoning: "Generated 24 enhanced photos, SEO-optimized description in Japanese targeting high-intent keywords. Recommended listing on 4 platforms simultaneously.",
    reasoningJa: "補正済み写真24枚、高意図キーワードをターゲットにしたSEO最適化説明文を生成。4プラットフォームへの同時出品を推奨。",
  },
]

export const activityFeed: ActivityEvent[] = [
  {
    id: "evt-001",
    agentId: "agent-pricing",
    agentName: "価格算定",
    action: "Completed market analysis for 8 vehicles",
    actionJa: "8台の市場分析を完了",
    timestamp: "2026-03-03T09:18:00Z",
    status: "success",
  },
  {
    id: "evt-002",
    agentId: "agent-procurement",
    agentName: "仕入",
    action: "Found 3 auction matches",
    actionJa: "3件のオークションマッチを検出",
    timestamp: "2026-03-03T09:15:00Z",
    status: "info",
    details: "USS Tokyo, HAA Kobe, JU Gifu",
    detailsJa: "USS東京、HAA神戸、JU岐阜",
  },
  {
    id: "evt-003",
    agentId: "agent-matching",
    agentName: "顧客マッチング",
    action: "Sent 5 personalized proposals",
    actionJa: "5件のパーソナライズ提案を送信",
    timestamp: "2026-03-03T09:12:00Z",
    status: "success",
  },
  {
    id: "evt-004",
    agentId: "agent-inspection",
    agentName: "車両検査",
    action: "Inspection report awaiting approval",
    actionJa: "検査レポートが承認待ち",
    timestamp: "2026-03-03T09:08:00Z",
    status: "warning",
  },
  {
    id: "evt-005",
    agentId: "agent-listing",
    agentName: "出品",
    action: "Listed Toyota RAV4 on 3 platforms",
    actionJa: "トヨタ RAV4 を3プラットフォームに出品完了",
    timestamp: "2026-03-03T09:05:00Z",
    status: "success",
  },
  {
    id: "evt-006",
    agentId: "agent-pricing",
    agentName: "価格算定",
    action: "Price reduction recommended for 2 vehicles",
    actionJa: "2台の値下げを提案",
    timestamp: "2026-03-03T09:00:00Z",
    status: "info",
  },
  {
    id: "evt-007",
    agentId: "agent-procurement",
    agentName: "仕入",
    action: "Won bid: Lexus NX 350h at USS Nagoya",
    actionJa: "落札成功: レクサス NX 350h USS名古屋",
    timestamp: "2026-03-03T08:55:00Z",
    status: "success",
    details: "Won at 3,420,000 JPY (budget: 3,600,000)",
    detailsJa: "342万円で落札（予算: 360万円）",
  },
  {
    id: "evt-008",
    agentId: "agent-matching",
    agentName: "顧客マッチング",
    action: "Customer inquiry auto-responded",
    actionJa: "顧客問い合わせに自動返信",
    timestamp: "2026-03-03T08:48:00Z",
    status: "success",
  },
  {
    id: "evt-009",
    agentId: "agent-listing",
    agentName: "出品",
    action: "Photo enhancement pipeline failed",
    actionJa: "写真補正パイプラインがエラー",
    timestamp: "2026-03-03T08:42:00Z",
    status: "error",
    details: "Retrying with fallback model",
    detailsJa: "フォールバックモデルで再試行中",
  },
  {
    id: "evt-010",
    agentId: "agent-pricing",
    agentName: "価格算定",
    action: "Daily market report generated",
    actionJa: "日次市場レポートを生成",
    timestamp: "2026-03-03T08:30:00Z",
    status: "success",
  },
]

export const vehicles: Vehicle[] = [
  {
    id: "v-001",
    make: "Toyota",
    model: "Crown Crossover",
    year: 2023,
    mileage: 12000,
    purchasePrice: 4200000,
    suggestedPrice: 4980000,
    status: "listed",
    statusJa: "出品中",
    imageUrl: "/placeholder.svg?height=200&width=320",
    grade: "4.5",
    color: "Black",
    colorJa: "ブラック",
  },
  {
    id: "v-002",
    make: "Mercedes-Benz",
    model: "C200",
    year: 2021,
    mileage: 23000,
    purchasePrice: 2800000,
    suggestedPrice: 2980000,
    status: "listed",
    statusJa: "出品中",
    imageUrl: "/placeholder.svg?height=200&width=320",
    grade: "4.0",
    color: "Silver",
    colorJa: "シルバー",
  },
  {
    id: "v-003",
    make: "BMW",
    model: "320i M Sport",
    year: 2022,
    mileage: 18000,
    purchasePrice: 0,
    suggestedPrice: 4420000,
    status: "pending-purchase",
    statusJa: "仕入承認待ち",
    imageUrl: "/placeholder.svg?height=200&width=320",
    grade: "4.5",
    color: "White",
    colorJa: "ホワイト",
  },
  {
    id: "v-004",
    make: "Honda",
    model: "Fit",
    year: 2023,
    mileage: 8000,
    purchasePrice: 1650000,
    suggestedPrice: 1980000,
    status: "in-inspection",
    statusJa: "検査中",
    imageUrl: "/placeholder.svg?height=200&width=320",
    grade: "B+",
    color: "Blue",
    colorJa: "ブルー",
  },
  {
    id: "v-005",
    make: "Toyota",
    model: "Alphard",
    year: 2023,
    mileage: 5000,
    purchasePrice: 5200000,
    suggestedPrice: 5980000,
    status: "listed",
    statusJa: "出品中",
    imageUrl: "/placeholder.svg?height=200&width=320",
    grade: "5.0",
    color: "White Pearl",
    colorJa: "ホワイトパール",
  },
]

export const kpis: KPI[] = [
  { label: "Monthly Revenue", labelJa: "月間売上", value: "47.2M", change: 12.5, trend: "up" },
  { label: "Active Inventory", labelJa: "在庫台数", value: "142", change: -3, trend: "down" },
  { label: "Avg Days to Sale", labelJa: "平均販売日数", value: "14.2", change: -18, trend: "up" },
  { label: "Token Efficiency", labelJa: "トークン効率", value: "94.2%", change: 2.1, trend: "up" },
]
